### ISSUE TITLE
unit tests -- ImportError: No module named symmetric_matrix

### ISSUE THREAD

**Issue by jborbely** [MSLNZ/GTC2#5]
When running the unit tests the following exception is raised
```python
Traceback (most recent call last):
  File "C:\Users\j.borbely\Miniconda3\envs\dev27\lib\unittest\case.py", line 329, in run
    testMethod()
  File "C:\Users\j.borbely\Miniconda3\envs\dev27\lib\unittest\loader.py", line 32, in testFailure
    raise exception
ImportError: Failed to import test module: test_symmetric_matrix
Traceback (most recent call last):
  File "C:\Users\j.borbely\Miniconda3\envs\dev27\lib\unittest\loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "C:\Users\j.borbely\Miniconda3\envs\dev27\lib\unittest\loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "C:\Users\j.borbely\code\git\GTC2\test\test_symmetric_matrix.py", line 10, in <module>
    from GTC.symmetric_matrix import SymmetricMatrix
ImportError: No module named symmetric_matrix
```

**Comment by BlairDHall** [comment]
This is due to a test module that is no longer needed (SymmetricMatrix is not used anymore)
